create extension if not exists pgcrypto;

create table if not exists public.later_space_items (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  kind text not null check (kind in ('image', 'video', 'link', 'text')),
  data jsonb not null default '{}'::jsonb check (jsonb_typeof(data) = 'object'),
  asset_path text,
  asset_bytes bigint not null default 0 check (asset_bytes >= 0),
  content_hash text,
  source_device_id text,
  client_updated_at bigint not null,
  server_updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  deleted_at timestamptz,
  revision bigint not null default 1
);

alter table public.later_space_items
  add column if not exists created_at timestamptz not null default now();

alter table public.later_space_items
  add column if not exists asset_bytes bigint not null default 0;

alter table public.later_space_items
  add column if not exists content_hash text;

create index if not exists later_space_items_user_sync_idx
  on public.later_space_items (user_id, server_updated_at);

create index if not exists later_space_items_user_active_idx
  on public.later_space_items (user_id, created_at)
  where deleted_at is null;

create unique index if not exists later_space_items_user_content_hash_idx
  on public.later_space_items (user_id, content_hash)
  where content_hash is not null and deleted_at is null;

create table if not exists public.later_space_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  data jsonb not null default '{}'::jsonb check (jsonb_typeof(data) = 'object'),
  client_updated_at bigint not null,
  server_updated_at timestamptz not null default now(),
  revision bigint not null default 1
);

create table if not exists public.later_space_capture_tokens (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  token_hash text not null unique check (length(token_hash) = 64),
  token_hint text not null check (length(token_hint) between 4 and 12),
  created_at timestamptz not null default now(),
  last_used_at timestamptz,
  revoked_at timestamptz
);

create index if not exists later_space_capture_tokens_user_idx
  on public.later_space_capture_tokens (user_id, created_at desc);

create table if not exists public.later_space_pwa_handoffs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  code_hash text not null unique check (length(code_hash) = 64),
  auth_token_hash text not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  consumed_at timestamptz
);

create index if not exists later_space_pwa_handoffs_user_idx
  on public.later_space_pwa_handoffs (user_id, created_at desc);

create table if not exists public.later_space_agent_tokens (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null default 'Agent',
  token_hash text not null unique check (length(token_hash) = 64),
  token_hint text not null check (length(token_hint) between 4 and 16),
  scope text not null default 'items:read' check (scope = 'items:read'),
  created_at timestamptz not null default now(),
  last_used_at timestamptz,
  revoked_at timestamptz
);

create index if not exists later_space_agent_tokens_user_idx
  on public.later_space_agent_tokens (user_id, created_at desc);

create table if not exists public.later_space_usage (
  user_id uuid primary key references auth.users(id) on delete cascade,
  used_bytes bigint not null default 0 check (used_bytes >= 0),
  quota_bytes bigint not null default 52428800 check (quota_bytes > 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.later_space_system_config (
  singleton boolean primary key default true check (singleton),
  used_bytes bigint not null default 0 check (used_bytes >= 0),
  quota_bytes bigint not null default 1073741824 check (quota_bytes > 0),
  warning_ratio numeric(4,3) not null default 0.700,
  urgent_ratio numeric(4,3) not null default 0.800,
  hard_stop_ratio numeric(4,3) not null default 0.850,
  image_uploads_enabled boolean not null default true,
  updated_at timestamptz not null default now(),
  check (warning_ratio > 0 and warning_ratio < urgent_ratio),
  check (urgent_ratio < hard_stop_ratio and hard_stop_ratio < 1)
);

insert into public.later_space_system_config (singleton)
values (true)
on conflict (singleton) do nothing;

create table if not exists public.later_space_admin_alerts (
  id bigint generated by default as identity primary key,
  level text not null check (level in ('warning', 'urgent', 'blocked')),
  scope text not null check (scope in ('system', 'user')),
  user_id uuid references auth.users(id) on delete cascade,
  used_bytes bigint not null,
  quota_bytes bigint not null,
  created_at timestamptz not null default now(),
  acknowledged_at timestamptz
);

create or replace function public.touch_later_space_row()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  if tg_op = 'UPDATE' then
    if new.client_updated_at < old.client_updated_at then
      return old;
    end if;
    if tg_table_name = 'later_space_items'
      and new.client_updated_at = old.client_updated_at
      and old.deleted_at is not null
      and new.deleted_at is null then
      return old;
    end if;
    new.revision = old.revision + 1;
  end if;
  new.server_updated_at = now();
  return new;
end;
$$;

drop trigger if exists touch_later_space_items on public.later_space_items;
create trigger touch_later_space_items
before update on public.later_space_items
for each row execute function public.touch_later_space_row();

drop trigger if exists touch_later_space_settings on public.later_space_settings;
create trigger touch_later_space_settings
before update on public.later_space_settings
for each row execute function public.touch_later_space_row();

alter table public.later_space_items enable row level security;
alter table public.later_space_settings enable row level security;
alter table public.later_space_capture_tokens enable row level security;
alter table public.later_space_pwa_handoffs enable row level security;
alter table public.later_space_agent_tokens enable row level security;
alter table public.later_space_usage enable row level security;
alter table public.later_space_system_config enable row level security;
alter table public.later_space_admin_alerts enable row level security;

do $$
begin
  alter publication supabase_realtime add table public.later_space_items;
exception
  when duplicate_object then null;
end;
$$;

grant select, insert, update, delete on public.later_space_items to authenticated;
grant select, insert, update, delete on public.later_space_settings to authenticated;
grant select, insert, update, delete on public.later_space_capture_tokens to authenticated;
grant select, insert, update, delete on public.later_space_agent_tokens to authenticated;
grant select on public.later_space_usage to authenticated;

revoke all on public.later_space_pwa_handoffs from public, anon, authenticated;

drop policy if exists "Users read own Later Space items" on public.later_space_items;
create policy "Users read own Later Space items"
on public.later_space_items for select
using (auth.uid() = user_id);

drop policy if exists "Users insert own Later Space items" on public.later_space_items;
create policy "Users insert own Later Space items"
on public.later_space_items for insert
with check (auth.uid() = user_id);

drop policy if exists "Users update own Later Space items" on public.later_space_items;
create policy "Users update own Later Space items"
on public.later_space_items for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users delete own Later Space items" on public.later_space_items;
create policy "Users delete own Later Space items"
on public.later_space_items for delete
using (auth.uid() = user_id);

drop policy if exists "Users read own Later Space settings" on public.later_space_settings;
create policy "Users read own Later Space settings"
on public.later_space_settings for select
using (auth.uid() = user_id);

drop policy if exists "Users insert own Later Space settings" on public.later_space_settings;
create policy "Users insert own Later Space settings"
on public.later_space_settings for insert
with check (auth.uid() = user_id);

drop policy if exists "Users update own Later Space settings" on public.later_space_settings;
create policy "Users update own Later Space settings"
on public.later_space_settings for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users read own Later Space capture tokens" on public.later_space_capture_tokens;
create policy "Users read own Later Space capture tokens"
on public.later_space_capture_tokens for select
using (auth.uid() = user_id);

drop policy if exists "Users create own Later Space capture tokens" on public.later_space_capture_tokens;
create policy "Users create own Later Space capture tokens"
on public.later_space_capture_tokens for insert
with check (auth.uid() = user_id);

drop policy if exists "Users revoke own Later Space capture tokens" on public.later_space_capture_tokens;
create policy "Users revoke own Later Space capture tokens"
on public.later_space_capture_tokens for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users delete own Later Space capture tokens" on public.later_space_capture_tokens;
create policy "Users delete own Later Space capture tokens"
on public.later_space_capture_tokens for delete
using (auth.uid() = user_id);

drop policy if exists "Users read own Later Space agent tokens" on public.later_space_agent_tokens;
create policy "Users read own Later Space agent tokens"
on public.later_space_agent_tokens for select
using (auth.uid() = user_id);

drop policy if exists "Users create own Later Space agent tokens" on public.later_space_agent_tokens;
create policy "Users create own Later Space agent tokens"
on public.later_space_agent_tokens for insert
with check (auth.uid() = user_id);

drop policy if exists "Users revoke own Later Space agent tokens" on public.later_space_agent_tokens;
create policy "Users revoke own Later Space agent tokens"
on public.later_space_agent_tokens for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users delete own Later Space agent tokens" on public.later_space_agent_tokens;
create policy "Users delete own Later Space agent tokens"
on public.later_space_agent_tokens for delete
using (auth.uid() = user_id);

drop policy if exists "Users read own Later Space usage" on public.later_space_usage;
create policy "Users read own Later Space usage"
on public.later_space_usage for select
using (auth.uid() = user_id);

create or replace function public.reserve_later_space_storage(p_user_id uuid, p_bytes bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  user_usage public.later_space_usage%rowtype;
  system_usage public.later_space_system_config%rowtype;
  next_user_bytes bigint;
  next_system_bytes bigint;
  user_limit bigint;
  system_limit bigint;
  previous_system_ratio numeric;
  next_system_ratio numeric;
begin
  if p_user_id is null or p_bytes is null or p_bytes <= 0 then
    return jsonb_build_object('ok', false, 'code', 'invalid_size');
  end if;

  perform pg_advisory_xact_lock(hashtext('later-space-storage'));

  insert into public.later_space_usage (user_id)
  values (p_user_id)
  on conflict (user_id) do nothing;

  select * into user_usage
  from public.later_space_usage
  where user_id = p_user_id
  for update;

  select * into system_usage
  from public.later_space_system_config
  where singleton = true
  for update;

  if not system_usage.image_uploads_enabled then
    return jsonb_build_object('ok', false, 'code', 'image_uploads_disabled');
  end if;

  next_user_bytes := user_usage.used_bytes + p_bytes;
  next_system_bytes := system_usage.used_bytes + p_bytes;
  user_limit := floor(user_usage.quota_bytes * system_usage.hard_stop_ratio)::bigint;
  system_limit := floor(system_usage.quota_bytes * system_usage.hard_stop_ratio)::bigint;

  if next_user_bytes > user_limit then
    return jsonb_build_object(
      'ok', false,
      'code', 'user_storage_full',
      'usedBytes', user_usage.used_bytes,
      'quotaBytes', user_usage.quota_bytes,
      'hardLimitBytes', user_limit
    );
  end if;

  if next_system_bytes > system_limit then
    insert into public.later_space_admin_alerts (level, scope, used_bytes, quota_bytes)
    values ('blocked', 'system', system_usage.used_bytes, system_usage.quota_bytes);
    return jsonb_build_object(
      'ok', false,
      'code', 'system_storage_full',
      'usedBytes', system_usage.used_bytes,
      'quotaBytes', system_usage.quota_bytes,
      'hardLimitBytes', system_limit
    );
  end if;

  previous_system_ratio := system_usage.used_bytes::numeric / system_usage.quota_bytes;
  next_system_ratio := next_system_bytes::numeric / system_usage.quota_bytes;

  update public.later_space_usage
  set used_bytes = next_user_bytes, updated_at = now()
  where user_id = p_user_id;

  update public.later_space_system_config
  set used_bytes = next_system_bytes, updated_at = now()
  where singleton = true;

  if previous_system_ratio < system_usage.warning_ratio and next_system_ratio >= system_usage.warning_ratio then
    insert into public.later_space_admin_alerts (level, scope, used_bytes, quota_bytes)
    values ('warning', 'system', next_system_bytes, system_usage.quota_bytes);
  end if;

  if previous_system_ratio < system_usage.urgent_ratio and next_system_ratio >= system_usage.urgent_ratio then
    insert into public.later_space_admin_alerts (level, scope, used_bytes, quota_bytes)
    values ('urgent', 'system', next_system_bytes, system_usage.quota_bytes);
  end if;

  return jsonb_build_object(
    'ok', true,
    'usedBytes', next_user_bytes,
    'quotaBytes', user_usage.quota_bytes,
    'systemRatio', next_system_ratio,
    'warningRatio', system_usage.warning_ratio,
    'urgentRatio', system_usage.urgent_ratio,
    'hardStopRatio', system_usage.hard_stop_ratio
  );
end;
$$;

create or replace function public.release_later_space_storage(p_user_id uuid, p_bytes bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_user_id is null or p_bytes is null or p_bytes <= 0 then
    return;
  end if;

  perform pg_advisory_xact_lock(hashtext('later-space-storage'));

  update public.later_space_usage
  set used_bytes = greatest(0, used_bytes - p_bytes), updated_at = now()
  where user_id = p_user_id;

  update public.later_space_system_config
  set used_bytes = greatest(0, used_bytes - p_bytes), updated_at = now()
  where singleton = true;
end;
$$;

revoke all on function public.reserve_later_space_storage(uuid, bigint) from public, anon, authenticated;
revoke all on function public.release_later_space_storage(uuid, bigint) from public, anon, authenticated;
grant execute on function public.reserve_later_space_storage(uuid, bigint) to service_role;
grant execute on function public.release_later_space_storage(uuid, bigint) to service_role;

create or replace function public.consume_later_space_pwa_handoff(p_code_hash text)
returns table(auth_token_hash text)
language sql
security definer
set search_path = public
as $$
  update public.later_space_pwa_handoffs as handoff
  set consumed_at = now()
  where handoff.code_hash = p_code_hash
    and handoff.consumed_at is null
    and handoff.expires_at > now()
  returning handoff.auth_token_hash;
$$;

revoke all on function public.consume_later_space_pwa_handoff(text) from public, anon, authenticated;
grant execute on function public.consume_later_space_pwa_handoff(text) to service_role;

insert into storage.buckets (id, name, public, file_size_limit)
values ('later-space-media', 'later-space-media', false, 5242880)
on conflict (id) do update set public = false, file_size_limit = excluded.file_size_limit;

drop policy if exists "Users read own Later Space media" on storage.objects;
create policy "Users read own Later Space media"
on storage.objects for select
using (bucket_id = 'later-space-media' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "Users upload own Later Space media" on storage.objects;
drop policy if exists "Users update own Later Space media" on storage.objects;
drop policy if exists "Users delete own Later Space media" on storage.objects;
